### ISSUE TITLE
some questions about different batch_size or cs_rate

### ISSUE THREAD

**Issue by dawnlh** [BoChenGroup/BIRNAT#1]
In line 161 of models.py (backrnn part), the code 
`out[:, Cr - 1, :, :] = xt` will cause error when batch_size> 1, Perhaps  it should be 
`out[:, Cr - 1, :, :] = xt[:, 0, :, :]`? Not quite sure~

And the file gan_resnet.py seems only work with cs_rate=8, how should I adapt it to work with other cs_rates?
looking forward to your reply!

**Comment by zihengcheng** [comment]
Hi dawnlh,
Sorry to reply you so late. You are right about the first problem, and this bug may be  due to a version change.

You can change the first parameter in line 30 of gan_resent.py
```self.conv_img = nn.Conv2d(8, 1 * nf, 3, padding=1)```
to change the cs_rate.

**Comment by dawnlh** [comment]
got it, Thanks a lot!
