### ISSUE TITLE
Reproducing training procedure Ubuntu 18.04

### ISSUE THREAD

**Issue by bryanbocao** [BoChenGroup/BIRNAT#6]
Dear Authors, thanks for sharing the code! I was trying to reproduce the training procedure on Ubuntu 18.04.

When I run ```python3 train.py```, I got
```
python3 train.py 
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    dataset = Imgdataset(data_path)
  File "/share/home/brcao/Repos/BIRNAT/dataLoadess.py", line 23, in __init__
    raise FileNotFoundError('path doesnt exist!')
FileNotFoundError: path doesnt exist!
```

Then I go back to generate the training data accordingly. First install MATLAB, download the TrainVal 480p Semi-supervised from [DAVIS2017](https://davischallenge.org/davis2017/code.html) and put it in the following folder: '/BIRNAT/data/DAVIS/',

![Screenshot from 2023-02-19 18-02-16](https://user-images.githubusercontent.com/14010288/219980581-d6b7903d-6f6c-4e14-a262-c4875e3d1209.png)
but it doesn't seem working. Any help would be great. Thanks!

**Comment by hopesala** [comment]
video_path=‘./data/DAVIS’ is OK, JPEGImages/480p is not needed @bryanbocao

**Comment by bryanbocao** [comment]
@hopesala Thanks for your reply.

Fixed it by
```
video_path = '../data/DAVIS/'
```
where folder structure is as follows
```
BIRNAT/
    |data/DAVIS/
    |train/data_generation.m
```

![Screenshot from 2023-02-25 21-17-36](https://user-images.githubusercontent.com/14010288/221388630-fb6cfa81-e0cf-4fa7-8467-ccfc7c800977.png)
